name: 'OpenAI Release Analyzer'
description: 'Analyzes release return messages from OpenAI API and provides insights.'
author: 'Nikhil Surendran'
inputs:
  OPENAI_API_KEY:
    description: 'Your OpenAI API key'
    required: true
  PROMPT:
    description: 'Prompt to analyze the logs'
    required: true
  LOG_FILE:
    description: 'Path to the file containing contents to analyze' 
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
    PROMPT: ${{ inputs.PROMPT }}
    LOG_FILE: ${{ inputs.LOG_FILE }}
