name: Release Management

on:
  push:
    paths:
      - 'release.log'

  workflow_dispatch:
  # This allows manual triggering of the workflow from the GitHub Actions UI
  # Useful for testing or running the workflow on demand  
    inputs:
      PROMPT:
        description: 'Prompt to analyze the logs'
        required: true
        default: 'Show me current services in Tabular format'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Custom Log Analyzer
        uses: ./actions/openai-release
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PROMPT: "Summarize the log"
          LOG_FILE: "sample.log"
